import test from 'node:test';
import assert from 'node:assert/strict';
import {ledger,validateLedger,persistLedger,loadLedger,importLedger,STORAGE_KEY} from '../shared/portfolio.mjs';
const products=[{id:'coin'},{id:'bar'}];
const tx=(changes={})=>({id:'1',product:'coin',type:'buy',quantity:3,unitPriceCents:10000,feesCents:101,date:'2026-01-01',note:'',...changes});
const memory=()=>{const m=new Map();return {getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,v)}};
test('buys include fees in cost basis',()=>{const s=ledger([tx()],products);assert.equal(s.holdings[0].costCents,30101);assert.equal(s.holdings[0].quantity,3);});
test('FIFO and partial lot fee allocation conserve cents',()=>{const result=ledger([tx(),tx({id:'2',quantity:2,unitPriceCents:12000,feesCents:0,date:'2026-01-02'}),tx({id:'3',type:'sell',quantity:4,unitPriceCents:15000,feesCents:100,date:'2026-01-03'})],products);assert.equal(result.realizedCents,17799);assert.equal(result.holdings[0].costCents,12000);});
test('three partial sales exhaust all cost-basis cents',()=>{const sales=[1,2,3].map((n)=>tx({id:String(n+1),type:'sell',quantity:1,unitPriceCents:15000,feesCents:0,date:`2026-01-0${n+1}`}));const r=ledger([tx(),...sales],products);assert.equal(r.realizedCents,45000-30101);assert.equal(r.holdings[0].costCents,0);});
test('oversell is rejected',()=>assert.throws(()=>ledger([tx(),tx({id:'2',type:'sell',quantity:4})],products),/supérieure/));
test('backdated sale validates historical availability',()=>assert.throws(()=>ledger([tx(),tx({id:'2',type:'sell',quantity:1,date:'2025-12-31'})],products),/supérieure/));
test('stable same-day ordering is retained',()=>{assert.doesNotThrow(()=>ledger([tx(),tx({id:'2',type:'sell',quantity:1})],products));assert.throws(()=>ledger([tx({id:'2',type:'sell',quantity:1}),tx()],products));});
test('invalid inputs rejected before mutation',()=>{for(const value of [{quantity:0},{quantity:1.5},{unitPriceCents:NaN},{feesCents:-1},{product:'unknown'},{date:'2026-02-30'},{date:'3000-01-01'},{note:'x'.repeat(501)}])assert.throws(()=>validateLedger([tx(value)],products));});
test('duplicate IDs rejected',()=>assert.throws(()=>validateLedger([tx(),tx()],products)));
test('storage roundtrip and absent storage',()=>{const storage=memory();assert.deepEqual(loadLedger(storage,products),[]);const valid=persistLedger(storage,[tx()],products);assert.deepEqual(loadLedger(storage,products),valid);});
test('corrupt storage does not silently become empty',()=>{const storage=memory();storage.setItem(STORAGE_KEY,'broken');assert.throws(()=>loadLedger(storage,products),/illisible/);assert.equal(storage.getItem(STORAGE_KEY),'broken');});
test('quota failures propagate so caller keeps previous data',()=>{assert.throws(()=>persistLedger({setItem:()=>{throw Error('quota')}},[tx()],products),/quota/);});
test('backup import is idempotent and conflict aware',()=>{const current=validateLedger([tx()],products);const data=JSON.stringify({schemaVersion:1,transactions:current});assert.deepEqual(importLedger(data,current,products),current);assert.throws(()=>importLedger(JSON.stringify({schemaVersion:1,transactions:[tx({unitPriceCents:1})]}),current,products),/Conflit/);});
test('backup import rejects future schema and oversells',()=>{assert.throws(()=>importLedger('{"schemaVersion":2,"transactions":[]}',[],products));assert.throws(()=>importLedger(JSON.stringify({schemaVersion:1,transactions:[tx({type:'sell'})]}),[],products));});
test('multiple products maintain independent inventory',()=>{const result=ledger([tx(),tx({id:'2',product:'bar',quantity:2})],products);assert.equal(result.holdings.length,2);assert.equal(result.holdings[1].quantity,2);});
