import {DEFAULTS,settings,analyze,crossDealer,backtest,dealerRows,costs,premium,parisDay,fresh,compareMarket,comparable,priceTime,minimumOK,unitPrice} from './shared/model.mjs';
import {ledger,loadLedger,persistLedger,importLedger,STORAGE_KEY} from './shared/portfolio.mjs';
import {lineChart,escapeHtml as e} from './chart.mjs';
const $=id=>document.getElementById(id),money=n=>n==null?'—':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(n/100);
const number=n=>new Intl.NumberFormat('fr-FR',{maximumFractionDigits:2}).format(n),pct=n=>n==null?'—':`${n>0?'+':''}${number(n)} %`;
const dateTime=s=>s?new Intl.DateTimeFormat('fr-FR',{timeZone:'Europe/Paris',day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(s)):'—';
const today=()=>new Date().toISOString().slice(0,10),now=()=>new Date().toISOString(),PREF='vivienne.settings.v1';
let products=[],dealers=[],market=null,config=settings(),serverConfig=settings(),transactions=[],storageLocked=false,activeTab='market',metal='gold',selected='coq20',period=90,area='all',selectedDealer='all',sortSide='ask',notification={status:'configuration_required'},toastTimer;
const label=id=>products.find(p=>p.id===id)?.label||id,dealer=id=>dealers.find(d=>d.id===id)||{label:id,address:''};
const external=(url,text)=>{try{const u=new URL(url);if(u.protocol!=='https:')return e(text);return `<a href="${e(url)}" target="_blank" rel="noopener noreferrer" class="external-link">${e(text)} ↗</a>`;}catch{return e(text);}};
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000);}
function report(message){$('global-error').textContent=message;$('global-error').hidden=false;}
async function json(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw Error(`Chargement impossible (${r.status}).`);return r.json();}
function switchTab(tab){activeTab=tab;document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==`view-${tab}`);document.querySelectorAll('.nav-button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false');});if(tab==='portfolio')renderPortfolio();if(tab==='signals')renderSignals();if(tab==='settings')renderSettings();}
function updateProductSelect(){const available=products.filter(p=>p.metal===metal);if(!available.some(p=>p.id===selected))selected=available[0].id;$('product-select').innerHTML=available.map(p=>`<option value="${p.id}">${e(p.label)}</option>`).join('');$('product-select').value=selected;document.querySelectorAll('[data-metal]').forEach(b=>{b.classList.toggle('selected',b.dataset.metal===metal);b.setAttribute('aria-pressed',String(b.dataset.metal===metal));});}
function scopedMarket(){const ids=new Set(dealers.filter(d=>(area==='all'||d.area===area)&&(selectedDealer==='all'||d.id===selectedDealer)).map(d=>d.id));return {...market,quotes:market.quotes.filter(q=>ids.has(q.dealer)),history:market.history.filter(q=>ids.has(q.dealer))};}
function renderSpots(){
  const at=now(),ok=market.health.filter(h=>h.status==='ok'&&fresh({observedAt:h.checkedAt},at,config.maxAgeHours)).length,total=market.health.length;
  const latest=market.quotes.map(q=>q.observedAt).sort().at(-1),isFresh=latest&&fresh({observedAt:latest},at,config.maxAgeHours);
  const covered=new Set(market.quotes.map(q=>q.dealer)).size;
  $('spot-strip').innerHTML=['gold','silver'].map(m=>{const s=market.spots.find(x=>x.metal===m),healthy=s&&fresh(s,at,config.maxAgeHours)&&!market.health.some(h=>h.id===s.source&&h.status!=='ok');return `<div class="spot-block"><span class="metal-symbol ${m==='silver'?'silver':''}">${m==='gold'?'Au':'Ag'}</span><div><div class="spot-label">${m==='gold'?'Or':'Argent'} · spot indicatif ${!healthy?'· ancien':''}</div><div class="spot-value">${s?number(s.eurPerGram):'—'} <small>€/g</small></div></div></div>`;}).join('')+`<div class="spot-health"><strong><i class="status-dot ${ok<total||!isFresh?'warn':''}"></i>${isFresh?'Dernier relevé':'Relevé ancien'} · ${e(dateTime(latest))}</strong><span>${covered} boutiques · ${new Set(market.quotes.map(q=>q.product)).size} produits · ${ok}/${total} sources récentes</span><span>Spot affiché par Change Vivienne</span></div>`;
  $('freshness-note').textContent=`Publication : ${dateTime(market.generatedAt)}. Collecte prévue toutes les 15 min, avec retards possibles de GitHub. Cette page recharge le dernier fichier publié ; elle ne lance pas une collecte. Seuil de fraîcheur : ${config.maxAgeHours} h.`;
}
function renderCoverage(){
  const covered=dealers.filter(d=>market.quotes.some(q=>q.dealer===d.id));
  $('coverage-count').textContent=`${covered.length} boutiques · ${covered.filter(d=>d.area==='vivienne').length} rue Vivienne`;
  $('shop-directory').innerHTML=covered.map(d=>{const qs=market.quotes.filter(q=>q.dealer===d.id),count=new Set(qs.map(q=>q.product)).size,healthy=qs.some(q=>fresh(q,now(),config.maxAgeHours)&&!q.confirmationRequired&&!market.health.some(h=>h.id===q.source&&h.status!=='ok')),note=qs.find(q=>q.confirmationRequired)?.confirmationRequired;return `<article class="shop-card"><h3>${external(d.url,d.label)}</h3><p>${e(d.address)}</p><span class="pill ${healthy?'good':'warning'}">${count} produits · ${note?'à confirmer':healthy?'relevés récents':'cours anciens / erreur'}</span>${note?`<p class="small-note">${e(note)}</p>`:''}<button class="text-button" data-shop="${d.id}">Comparer cette boutique</button></article>`;}).join('');
}
function historyPoints(){const dayMap=new Map(),cutoff=Date.now()-period*86400000;for(const q of scopedMarket().history.filter(q=>q.product===selected&&!q.confirmationRequired&&fresh(q,q.observedAt,config.maxAgeHours)&&new Date(priceTime(q))>=cutoff).sort((a,b)=>new Date(a.observedAt)-new Date(b.observedAt))){const d=parisDay(priceTime(q));if(!dayMap.has(d))dayMap.set(d,new Map());dayMap.get(d).set(q.source,q);}return [...dayMap].sort(([a],[b])=>a.localeCompare(b)).map(([d,rows])=>{const qs=[...rows.values()],asks=qs.filter(q=>minimumOK(q,'ask',config.tradeQuantity)).map(q=>unitPrice(q,'ask',config.tradeQuantity)).filter(Number.isFinite),bids=qs.filter(q=>minimumOK(q,'bid',config.tradeQuantity)).map(q=>unitPrice(q,'bid',config.tradeQuantity)).filter(Number.isFinite),melt=qs.filter(q=>Number.isFinite(q.meltCents)).sort((a,b)=>new Date(b.observedAt)-new Date(a.observedAt))[0]?.meltCents;return {day:d,label:new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short'}).format(new Date(d+'T12:00:00Z')),ask:asks.length?Math.min(...asks):null,bid:bids.length?Math.max(...bids):null,melt:melt??null};});}
function renderChart(){const points=historyPoints(),series=[{key:'ask',label:'Vous payez',color:'#a27928'},{key:'bid',label:'Vous recevez',color:'#326a9a'},{key:'melt',label:'Valeur métal',color:'#81909e',dash:true}].filter(s=>$(`line-${s.key}`).checked);$('price-chart').innerHTML=lineChart(points,series,{label:`Historique · ${label(selected)}`});$('chart-note').textContent=points.length<2?`${points.length} journée observée. La courbe se construira au fil des collectes, sans données fictives.`:`${points.length} journées observées. Prix par unité pour ${config.tradeQuantity} unité(s), minimums vérifiés. Relevés non simultanés ; disponibilité à confirmer.`;$('history-table').innerHTML=`<table><thead><tr><th>Date</th><th class="numeric">Vous payez</th><th class="numeric">Vous recevez</th><th class="numeric">Métal</th></tr></thead><tbody>${points.map(p=>`<tr><td>${e(p.day)}</td><td class="numeric">${money(p.ask)}</td><td class="numeric">${money(p.bid)}</td><td class="numeric">${money(p.melt)}</td></tr>`).join('')}</tbody></table>`;}
function quoteCell(q,side,best){
  if(!q)return '<span class="small-note">Non publié / indisponible</span>';
  const min=q[side==='ask'?'minBuy':'minSell'],max=q[side==='ask'?'maxBuy':'maxSell'],eligible=comparable(q,side,config.tradeQuantity);
  const note=q.confirmationRequired?'Confirmation requise':!q.valid?'Ancien / erreur':!eligible?'Quantité non vérifiée ou hors plage':'';
  return `<span class="price-cell ${eligible&&q.value===best?.value?'best':''} ${!q.valid?'old-price':''}">${money(q.value)}</span><span class="small-note">Min. ${min??'à vérifier'}${max?' · max. '+max:''}${note?' · '+note:''}</span>${external(q.url,'Voir le prix')}${q.priceNote?`<details class="quote-detail"><summary>Conditions</summary>${e(q.priceNote)}</details>`:''}`;
}
function renderMarket(){
  if(!market)return;updateProductSelect();renderSpots();
  const dealerOptions=dealers.filter(d=>area==='all'||d.area===area);
  if(selectedDealer!=='all'&&!dealerOptions.some(d=>d.id===selectedDealer))selectedDealer='all';
  $('dealer-select').innerHTML='<option value="all">Toutes les boutiques</option>'+dealerOptions.map(d=>`<option value="${d.id}">${e(d.label)}</option>`).join('');$('dealer-select').value=selectedDealer;$('compare-quantity').value=config.tradeQuantity;
  for(const [attr,value] of [['area',area],['sort',sortSide]])document.querySelectorAll(`[data-${attr}]`).forEach(b=>{b.classList.toggle('selected',b.dataset[attr]===value);b.setAttribute('aria-pressed',String(b.dataset[attr]===value));});
  const product=products.find(p=>p.id===selected),view=scopedMarket(),comparison=compareMarket(view,product,config,now()),{ask,bid}=comparison;
  const rows=[...comparison.rows].sort((a,b)=>{const qa=a[sortSide],qb=b[sortSide],va=comparable(qa,sortSide,config.tradeQuantity),vb=comparable(qb,sortSide,config.tradeQuantity);return Number(vb)-Number(va)||(sortSide==='ask'?(qa?.value??Infinity)-(qb?.value??Infinity):(qb?.value??-Infinity)-(qa?.value??-Infinity))||dealer(a.dealer).label.localeCompare(dealer(b.dealer).label);});
  const spot=market.spots.find(s=>s.metal===product.metal),spotOK=spot&&fresh(spot,now(),config.maxAgeHours)&&!market.health.some(h=>h.id===spot.source&&h.status!=='ok'),melt=spotOK?Math.round(product.fineGrams*spot.eurPerGram*100):null;
  const totals=costs(ask?.value,bid?.value,config.tradeQuantity,config),spread=totals.edgePct,analysis=analyze(view,product,config,now()),days=Math.max(0,...analysis.signals.map(s=>s.days));
  $('product-spec').textContent=`${number(product.fineGrams)} g de métal fin · prix par unité`;$('chart-title').textContent=product.label;
  $('comparison-context').textContent=`${rows.length} boutiques pour ce produit · ${config.tradeQuantity} unité(s) · budget ${money(config.budgetCents)}`;
  $('product-summary').innerHTML=`<div class="summary-card primary"><p class="eyebrow">MEILLEUR ACHAT COMPARABLE</p><div class="summary-value" id="best-ask">${money(ask?.value)}</div><div class="sub">${ask?e(dealer(ask.dealer).label):'Aucun prix vérifié pour cette quantité'}</div><p class="small-note">${ask?`${config.tradeQuantity} unité(s), frais inclus : ${money(totals.buy)}${totals.buy>config.budgetCents?' · budget dépassé':''}`:'Voir les cours indicatifs dans le tableau.'}</p></div><div class="summary-card"><p class="eyebrow">MEILLEURE REVENTE COMPARABLE</p><div class="summary-value" id="best-bid">${money(bid?.value)}</div><div class="sub">${bid?e(dealer(bid.dealer).label):'Aucun prix vérifié pour cette quantité'}</div><p class="small-note">${bid?`${config.tradeQuantity} unité(s), net estimé : ${money(totals.sell)}`:'Minimums inconnus exclus du classement.'}</p></div><div class="summary-card"><div class="summary-split"><div><p class="eyebrow">VALEUR MÉTAL</p><div class="summary-small">${money(melt)}</div></div><div><p class="eyebrow">ÉCART NET*</p><div class="summary-small">${spread==null?'—':number(-spread)+' %'}</div></div></div><p class="sub" style="margin-top:10px">* Achat puis revente, frais inclus.<br>Modèle : ${days}/${config.minDays} jours précédents.</p></div>`;
  $('dealer-table').innerHTML=rows.length?`<table><thead><tr><th>Boutique</th><th class="numeric">Vous payez / unité</th><th class="numeric">Vous recevez / unité</th><th class="numeric">Prime d’achat</th><th class="numeric">Spread brut</th><th>Relevé / date du cours</th></tr></thead><tbody>${rows.map(r=>{const a=r.ask,b=r.bid,spread=a?.valid&&b?.valid?(a.value-b.value)/a.value*100:null;return `<tr data-dealer="${e(r.dealer)}"><td><span class="dealer-name">${e(dealer(r.dealer).label)}</span><span class="dealer-address">${e(dealer(r.dealer).address)}</span></td><td class="numeric" data-side="ask">${quoteCell(a,'ask',ask)}</td><td class="numeric" data-side="bid">${quoteCell(b,'bid',bid)}</td><td class="numeric">${pct(a?.valid?premium(a.value,melt):null)}</td><td class="numeric">${spread==null?'—':number(spread)+' %'}</td><td><span class="small-note">Achat : ${e(dateTime(a?.observedAt))}${a?.publishedAt?'<br>Cours : '+e(dateTime(a.publishedAt)):''}<br>Rachat : ${e(dateTime(b?.observedAt))}${b?.publishedAt?'<br>Cours : '+e(dateTime(b.publishedAt)):''}</span></td></tr>`;}).join('')}</tbody></table>`:'<div class="empty">Aucune boutique dans ce filtre ne publie un prix suivi pour ce produit.</div>';
  $('source-summary').textContent=`État des sources · ${market.health.filter(h=>h.status==='ok').length}/${market.health.length} lectures réussies`;$('sources-list').innerHTML=market.health.map(h=>`<div class="source-row"><div>${external(h.url,h.id)}<span class="small-note">Relevé ${e(dateTime(h.checkedAt))}${h.error?' · '+e(h.error):''}</span></div><span class="pill ${h.status==='ok'?'good':'warning'}">${h.status==='ok'?h.count+' prix':'Erreur'}</span></div>`).join('');renderCoverage();renderChart();
}
function state(){return ledger(transactions,products);}
function holdingValue(h){const rows=dealerRows(market.quotes,h.product,now(),{...config,tradeQuantity:h.quantity},market.health),best=rows.map(r=>r.bid).filter(q=>comparable(q,'bid',h.quantity)).sort((a,b)=>b.value-a.value)[0];return {best,value:best?costs(null,best.value,h.quantity,config).sell:null};}
function renderPortfolio(){if(!market)return;const s=state(),held=s.holdings.filter(h=>h.quantity),cost=held.reduce((a,h)=>a+h.costCents,0),values=held.map(holdingValue),missing=values.filter(v=>v.value==null).length,total=values.reduce((a,v)=>a+(v.value||0),0);$('portfolio-stats').innerHTML=[['Coût des avoirs',money(cost),'Frais d’acquisition inclus'],['Revente indicative',money(total),missing?`${missing} produit(s) sans cours frais · total partiel`:'Frais et provision fiscale déduits'],['Résultat réalisé',money(s.realizedCents),'FIFO · frais réels enregistrés']].map(([title,value,note])=>`<div class="stat-card"><div><p class="eyebrow">${e(title)}</p><div class="small-note">${e(note)}</div></div><div class="stat-number">${value}</div></div>`).join('');
  $('holdings').innerHTML=!held.length?'<div class="empty"><h3>Votre journal commence ici.</h3><p>Ajoutez vos pièces et lingots avec leur date et leur prix d’achat.</p><button class="button" data-add>Ajouter mon premier achat</button></div>':`<div class="table-scroll"><table><thead><tr><th>Produit</th><th class="numeric">Quantité</th><th class="numeric">Coût total</th><th class="numeric">Revente nette</th><th class="numeric">Écart latent</th><th>Lecture du marché</th></tr></thead><tbody>${held.map((h,i)=>{const {best,value}=values[i],profit=value==null?null:value-h.costCents,p=products.find(p=>p.id===h.product),sigs=analyze(market,p,{...config,tradeQuantity:h.quantity},now()).signals,sell=sigs.find(s=>s.type==='sell'&&s.excellent);return `<tr><td><strong>${e(label(h.product))}</strong></td><td class="numeric">${h.quantity}</td><td class="numeric">${money(h.costCents)}</td><td class="numeric">${money(value)}<span class="small-note">${best?e(dealer(best.dealer).label):'Cours manquant'}</span></td><td class="numeric ${profit>0?'positive':profit<0?'negative':''}">${money(profit)}</td><td><span class="pill ${sell&&profit>0?'good':''}">${sell&&profit>0?'Vente à étudier':'Aucun signal de vente'}</span><span class="holding-note">${best?.minSell==null?'Minimum de rachat à confirmer.':'Valeur indicative, état à confirmer.'}</span></td></tr>`;}).join('')}</tbody></table></div>`;
  $('transactions').innerHTML=!transactions.length?'<div class="empty compact-empty">Aucune opération enregistrée.</div>':`<table><thead><tr><th>Date</th><th>Opération</th><th>Produit</th><th class="numeric">Qté</th><th class="numeric">Prix unitaire</th><th class="numeric">Frais</th><th></th></tr></thead><tbody>${[...transactions].reverse().map(t=>`<tr><td>${e(t.date)}</td><td><span class="pill ${t.type==='buy'?'good':''}">${t.type==='buy'?'Achat':'Vente'}</span></td><td>${e(label(t.product))}${t.note?`<span class="small-note">${e(t.note)}</span>`:''}</td><td class="numeric">${t.quantity}</td><td class="numeric">${money(t.unitPriceCents)}</td><td class="numeric">${money(t.feesCents)}</td><td><button class="text-button" data-edit="${e(t.id)}">Modifier</button><button class="text-button danger" data-delete="${e(t.id)}">Supprimer</button></td></tr>`).join('')}</tbody></table>`;
  $('add-transaction').disabled=storageLocked;
}
function openTransaction(id){if(storageLocked){toast('Restaurez la sauvegarde avant de modifier le journal.');return;}const f=$('transaction-form');f.reset();f.elements.product.innerHTML=products.map(p=>`<option value="${p.id}">${e(p.label)}</option>`).join('');f.elements.product.value=selected;f.elements.date.value=today();f.elements.date.max=today();f.elements.id.value=id||'';$('transaction-error').textContent='';$('transaction-title').textContent=id?'Modifier une opération':'Ajouter une opération';if(id){const t=transactions.find(t=>t.id===id);for(const k of ['type','product','quantity','date','note'])f.elements[k].value=t[k];f.elements.price.value=t.unitPriceCents/100;f.elements.fees.value=t.feesCents/100;}$('transaction-dialog').showModal();}
function saveTransaction(input){if(storageLocked)throw Error('Journal verrouillé : sauvegarde illisible.');const t={id:input.id||crypto.randomUUID(),type:input.type,product:input.product,quantity:Number(input.quantity),date:input.date,unitPriceCents:Number(input.unitPriceCents),feesCents:Number(input.feesCents),note:input.note||''};const next=transactions.some(x=>x.id===t.id)?transactions.map(x=>x.id===t.id?t:x):[...transactions,t];transactions=persistLedger(localStorage,next,products);renderPortfolio();return t;}
function renderSignals(){if(!market)return;const all=products.flatMap(p=>analyze(market,p,config,now()).signals),excellent=all.filter(s=>s.excellent),days=Math.max(0,...all.map(s=>s.days));$('signal-status').textContent=excellent.length?`${excellent.length} signal(s) satisfont vos seuils. Vérifiez chaque prix en boutique avant une opération.`:days<config.minDays?`Le modèle apprend le marché : ${days}/${config.minDays} jours précédents disponibles. Aucun signal historique ne sera qualifié d’excellent avant ce seuil.`:'Aucune opportunité ne satisfait tous les critères actuellement. Les seuils restent inchangés.';
  const chosen=excellent.length?excellent:all.filter(s=>s.product===selected);$('signal-cards').innerHTML=chosen.length?chosen.map(s=>`<article class="signal-card"><span class="pill ${s.excellent?'good':''}">${s.excellent?'À étudier':'En observation'} · ${s.type==='buy'?'achat':'vente'}</span><h3>${e(label(s.product))}</h3><p class="muted">${e(dealer(s.dealer).label)}</p><div class="metric">${money(s.price)}</div><p class="small-note">Prime ${pct(s.premiumPct)} · z ${s.days?number(s.z):'—'}<br>${s.days} jours précédents · ${s.quantity} unité(s)</p><details><summary>${s.excellent?'Pourquoi ce signal ?':'Pourquoi attendre ?'}</summary><ul>${(s.excellent?[`Écart normalisé : ${number(s.z)}`,`Avantage estimé après frais : ${pct(s.edgePct)}`]:s.reasons).map(r=>`<li>${e(r)}</li>`).join('')}</ul></details><div style="margin-top:12px">${external(s.url,'Vérifier le cours')}</div></article>`).join(''):'<div class="empty">Aucun prix ne permet de calculer un signal pour ce produit.</div>';
  const cross=crossDealer(market,products.find(p=>p.id===selected),config,now());if(cross)$('signal-cards').insertAdjacentHTML('beforeend',`<article class="signal-card"><span class="pill ${cross.excellent?'good':''}">Écart entre boutiques</span><h3>${e(label(selected))}</h3><p class="muted">${e(dealer(cross.buyDealer).label)} → ${e(dealer(cross.sellDealer).label)}</p><div class="metric ${cross.edgePct>0?'positive':'negative'}">${pct(cross.edgePct)}</div><p class="small-note">Achat puis revente après frais. ${cross.synchronized?'Observations espacées de moins de 15 min.':'Observations non simultanées.'}</p></article>`);$('backtest-product').textContent=`Produit sélectionné : ${label(selected)} · règles actuelles · frais inclus`;
}
const fieldDefs={model:[['lookbackDays','Fenêtre historique (jours)',1,'30 à 730 jours'],['minDays','Minimum de jours distincts',1,'Pas de signal avant ce seuil'],['zThreshold','Écart normalisé minimum',.1,'2 = deux échelles robustes'],['maxPremiumPct','Prime d’achat maximale (%)',.1,'Au-dessus de la valeur métal'],['maxSpreadPct','Spread net maximal (%)',.1,'Coût d’un aller-retour'],['minEdgePct','Avantage net minimal (%)',.1,'Marge de sécurité après frais'],['maxAgeHours','Âge maximal d’un prix (h)',.25,'Les cours anciens sont exclus'],['cooldownHours','Délai entre emails (h)',1,'Pour un même produit et signal']],cost:[['budgetCents','Budget par achat (€)',.01,'Frais inclus'],['tradeQuantity','Quantité par opération',1,'Pièces ou lingots entiers'],['buyFeePct','Frais d’achat (%)',.1,'En plus du prix publié'],['sellFeePct','Frais de vente (%)',.1,'En plus du prix publié'],['taxPct','Provision fiscale vente (%)',.1,'À ajuster à votre situation'],['fixedFeeCents','Frais fixes par côté (€)',.01,'Transport, déplacement, etc.']]};
function renderSettings(){for(const [group,target] of [['model','model-fields'],['cost','cost-fields']])$(target).innerHTML=fieldDefs[group].map(([key,text,step,hint])=>`<label>${e(text)}<input type="number" name="${key}" step="${step}" value="${key.endsWith('Cents')?config[key]/100:config[key]}" required><span class="field-hint">${e(hint)}</span></label>`).join('');$('alert-enabled').checked=config.alertEnabled;const status={disabled:'Désactivées dans le dépôt',no_signal:'Actives · aucun signal',sent:'Dernier envoi effectué',configuration_required:'Secrets à configurer',dry_run:'Mode test',error:'Erreur d’envoi'};$('email-status').textContent=status[notification.status]||'État inconnu';}
function readFormSettings(){const values=Object.fromEntries(new FormData($('settings-form')).entries());for(const k of Object.keys(values))values[k]=k.endsWith('Cents')?Math.round(Number(values[k])*100):Number(values[k]);return settings({...values,alertEnabled:$('alert-enabled').checked});}
function saveSettings(next){const valid=settings(next);localStorage.setItem(PREF,JSON.stringify(valid));config=valid;renderMarket();return valid;}
function download(name,value){const url=URL.createObjectURL(new Blob([value],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function bind(){document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.tab)switchTab(b.dataset.tab);if(b.dataset.area){area=b.dataset.area;selectedDealer='all';renderMarket();}if(b.dataset.sort){sortSide=b.dataset.sort;renderMarket();}if(b.dataset.shop){area='all';selectedDealer=b.dataset.shop;renderMarket();$('dealer-select').focus();}if(b.dataset.metal){metal=b.dataset.metal;renderMarket();}if(b.dataset.period){period=Number(b.dataset.period);document.querySelectorAll('[data-period]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});renderChart();}if('add'in b.dataset)openTransaction();if(b.dataset.edit)openTransaction(b.dataset.edit);if(b.dataset.delete){if(!confirm('Supprimer cette opération ? Une sauvegarde exportée permet de la restaurer.'))return;try{transactions=persistLedger(localStorage,transactions.filter(t=>t.id!==b.dataset.delete),products);renderPortfolio();toast('Opération supprimée.');}catch(err){toast(err.message);}}});
  $('dealer-select').addEventListener('change',ev=>{selectedDealer=ev.target.value;renderMarket();});
  $('compare-quantity').addEventListener('change',ev=>{try{saveSettings({...config,tradeQuantity:Number(ev.target.value)});}catch(err){toast(err.message);ev.target.value=config.tradeQuantity;}});
  $('product-select').addEventListener('change',ev=>{selected=ev.target.value;renderMarket();});for(const k of ['ask','bid','melt'])$(`line-${k}`).addEventListener('change',renderChart);
  $('refresh').addEventListener('click',()=>refreshSnapshot());
  $('add-transaction').addEventListener('click',()=>openTransaction());for(const id of ['close-dialog','cancel-dialog'])$(id).addEventListener('click',()=>$('transaction-dialog').close());
  $('transaction-form').addEventListener('submit',ev=>{ev.preventDefault();try{const f=Object.fromEntries(new FormData(ev.target));saveTransaction({...f,unitPriceCents:Math.round(Number(f.price)*100),feesCents:Math.round(Number(f.fees)*100)});$('transaction-dialog').close();toast('Opération enregistrée dans ce navigateur.');}catch(err){$('transaction-error').textContent=err.message;}});
  $('export-backup').addEventListener('click',()=>{const raw=storageLocked?localStorage.getItem(STORAGE_KEY):JSON.stringify({schemaVersion:1,exportedAt:now(),transactions},null,2);download(`vivienne-sauvegarde-${today()}.json`,raw||'{}');toast('Sauvegarde exportée. Gardez-la dans un endroit privé.');});
  $('import-backup').addEventListener('click',()=>$('backup-file').click());$('backup-file').addEventListener('change',async ev=>{const file=ev.target.files[0];if(!file)return;try{if(file.size>10000000)throw Error('Fichier trop volumineux.');const next=importLedger(await file.text(),transactions,products,storageLocked?'replace':'merge');if(storageLocked&&!confirm('Remplacer le journal illisible par cette sauvegarde validée ?'))return;transactions=persistLedger(localStorage,next,products);storageLocked=false;$('global-error').hidden=true;renderPortfolio();toast('Sauvegarde importée et vérifiée.');}catch(err){toast(err.message);}finally{ev.target.value='';}});
  $('settings-form').addEventListener('submit',ev=>{ev.preventDefault();try{saveSettings(readFormSettings());toast('Paramètres locaux enregistrés. Les emails utilisent encore la configuration du dépôt.');}catch(err){toast(err.message);}});
  $('reset-settings').addEventListener('click',()=>{try{saveSettings(DEFAULTS);renderSettings();toast('Valeurs initiales restaurées.');}catch(err){toast(err.message);}});
  $('export-settings').addEventListener('click',()=>{try{const s=readFormSettings();download('settings.json',JSON.stringify(s,null,2));toast('Remplacez config/settings.json dans GitHub avec ce fichier.');}catch(err){toast(err.message);}});
  $('run-backtest').addEventListener('click',()=>{const result=backtest(market,products.find(p=>p.id===selected),config);if(!result.enoughHistory){$('backtest-result').innerHTML=`<div class="empty compact-empty">${result.days} journée(s) disponible(s). Il en faut au moins ${config.minDays+2} pour lancer une simulation exploitable.</div>`;return;}$('backtest-result').innerHTML=`<div class="backtest-grid"><span class="muted">Allers-retours<strong>${result.trades.length}</strong></span><span class="muted">Variation simulée<strong>${pct(result.returnPct)}</strong></span><span class="muted">Baisse maximale<strong>${number(result.maxDrawdownPct)} %</strong></span><span class="muted">Position ouverte<strong>${result.openPosition?'Oui':'Non'}</strong></span></div>${lineChart(result.equity.map(x=>({...x,label:x.day})),[{key:'valueCents',label:'Capital simulé',color:'#326a9a'}],{label:'Capital simulé dans le backtest'})}<p class="footnote">${e(result.note)} ${!result.trades.length?'Aucun aller-retour terminé : performance non validée.':''}</p>`;});
}
function registerTools(){const context=document.modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const register=tool=>{try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch{}};register({name:'get_market_snapshot',description:'Read the currently displayed product, dealer quotes and local model parameters.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({product:selected,quotes:market.quotes.filter(q=>q.product===selected),settings:config})});register({name:'record_portfolio_transaction',description:'Record a buy or sell in the private device-local journal; this does not execute a trade.',inputSchema:{type:'object',properties:{type:{enum:['buy','sell']},product:{type:'string'},quantity:{type:'integer'},date:{type:'string'},unitPriceCents:{type:'integer'},feesCents:{type:'integer'},note:{type:'string'}},required:['type','product','quantity','date','unitPriceCents','feesCents'],additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{const t=saveTransaction(input);switchTab('portfolio');return {id:t.id,transactionCount:transactions.length};}});window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}
async function refreshSnapshot(silent=false){const b=$('refresh');if(b.disabled)return;b.disabled=true;try{const next=await json('./data/market.json'),changed=next.generatedAt!==market.generatedAt;market=next;renderMarket();if(activeTab==='portfolio')renderPortfolio();if(activeTab==='signals')renderSignals();if(!silent)toast(changed?'Nouvelle publication chargée.':'Publication inchangée. Prochaine collecte selon le calendrier GitHub.');}catch(err){if(!silent)toast(err.message);}finally{b.disabled=false;}}
async function init(){try{[products,dealers,market,serverConfig]=await Promise.all([json('./config/products.json'),json('./config/dealers.json'),json('./data/market.json'),json('./config/settings.json')]);config=settings(serverConfig);try{const raw=localStorage.getItem(PREF);if(raw)config=settings(JSON.parse(raw));}catch{report('Les paramètres locaux sont illisibles. Les valeurs du dépôt sont utilisées.');}try{transactions=loadLedger(localStorage,products);}catch(err){storageLocked=true;report(err.message);}try{notification=await json('./data/notifications.json');}catch{}bind();renderMarket();renderSettings();$('clock').textContent=`Paris · ${new Intl.DateTimeFormat('fr-FR',{timeZone:'Europe/Paris',hour:'2-digit',minute:'2-digit'}).format(new Date())}`;registerTools();window.setInterval(()=>{if(!document.hidden&&!['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))refreshSnapshot(true);},60000);}catch(err){report('Les données ne sont pas disponibles. Réessayez après la prochaine publication. '+err.message);$('spot-strip').innerHTML='<p class="empty">Impossible de charger les prix.</p>';}}
init();
